### ISSUE TITLE
Mongolian text decoration styles

### ISSUE THREAD

**Issue by r12a** [w3c/mlreq#10]
from https://github.com/w3c/mlreq/issues/9

@siqinbilige wrote:
>  By the way, there are exists many line styles in mongolian.

![](https://cloud.githubusercontent.com/assets/13462439/24791374/d2180976-1bb4-11e7-8bc8-77f05a636079.png)

@siqinbilige that's a very handy example!  Do you have a slightly larger version that i could add to the type-samples repository?  (if so, please send me via email)

I believe all of those styles are covered by the [CSS3 spec](https://drafts.csswg.org/css-text-decor-3/#text-decoration-style-property).

However, i'd be very interested to know what is the meaning/purpose for each of those different styles.  Could you explain that for me?

**Comment by siqinbilige** [comment]
There is a large version of the picture.
Those different styles for analysis sentence patterns.
For example, subject , verb, ... etc.
In normally, there are five patterns in mongolian sentence.
![underlinestyles](https://cloud.githubusercontent.com/assets/13462439/24985478/568de012-202f-11e7-8dc2-56f2e3be8223.jpg)

**Comment by r12a** [comment]
thanks @siqinbilige. I believe that CSS can do all of these styles except the one that combines the straight and wavy lines.  That raises a couple of questions for me: Is that very common (in Mongolian and/or in Chinese)?  If the mongolian text is set horizontally, does the wavy line appear above or below the straight line?

**Comment by siqinbilige** [comment]
Yes, that is quite common in Mongolian, Chinese, and Japanese, I think.  For that purpose, Microsoft Office Word was fully prepared under line styles and colors in Japanese and Chinese version. We hope have a color option in under line, too.
In normally (Monglian thinking), if the mongolian text is set horizontally, the wavy line appear above (Counter-clockwise 90 deg). 
![underlinestylesandcolors](https://cloud.githubusercontent.com/assets/13462439/25031406/a95c882e-2107-11e7-8d85-aef6e7fe476a.png)
[toushisagi.pdf](https://github.com/w3c/mlreq/files/931870/toushisagi.pdf)
