### ISSUE TITLE
A isol 1 not decomposed, when A isol 3 is

### ISSUE THREAD

**Issue by r12a** [w3c/mlreq#12]
If i understand correctly, to represent isolated form no. 3 per the chart in section 1.2.2 of the graphetic model description, one has to use two graphetic characters, ie. 

![screen shot 2017-09-01 at 18 35 52](https://user-images.githubusercontent.com/4839211/29981115-6826a51e-8f44-11e7-9e99-aab112ab92fb.png)
equals
![screen shot 2017-09-01 at 18 36 20](https://user-images.githubusercontent.com/4839211/29981139-8057872a-8f44-11e7-8810-a34f25723627.png)
+
![screen shot 2017-09-01 at 18 36 32](https://user-images.githubusercontent.com/4839211/29981145-84e59480-8f44-11e7-90fd-f260c2b0a494.png)

Yet to represent 
![screen shot 2017-09-01 at 18 37 08](https://user-images.githubusercontent.com/4839211/29981167-9b805f5e-8f44-11e7-8017-17e66de18058.png)
one can do so with a single character, rather than using 
![screen shot 2017-09-01 at 18 36 20](https://user-images.githubusercontent.com/4839211/29981139-8057872a-8f44-11e7-8810-a34f25723627.png)
+
![screen shot 2017-09-01 at 18 38 03](https://user-images.githubusercontent.com/4839211/29981197-b4db6066-8f44-11e7-93f3-84ac33f5d9c6.png)

Is that correct?  And if so, why the discrepancy?

**Comment by lianghai** [comment]
`A.1.isol`'s toothless-left-tail (zero tooth) is simply an incidental feature of the tooth/cap when a tooth/cap ends a sequence but can't expand to a normal right-tail (one tooth), eg, a tooth on an isol position or on a fina position preceded by a round consonant (B, feminine G, etc).

One can only use the single tooth graphetic character to produce a shape like `A.1.isol` or `E.1.isol`. For modern Hudum there isn't a character for the jointed toothless-left-tail in the graphetic approach. The last image in your message is a non-joining character only used for the disjointed tail (čačulg_a / tsatslag) which is encoded `<MVS, A/E>` in the current encoding.

**Comment by lianghai** [comment]
Oops, sorry, Richard. Somehow I thought you were referring to my graphetic doc, but when you started mentioning "[section] 2.2.1" I became confused… There isn't a section 2.2.1 in my doc…
