### ISSUE TITLE
Missing glyph from U+1821 E in 1.2.2 ?

### ISSUE THREAD

**Issue by r12a** [w3c/mlreq#13]
The table in 1.2.2 representing U+1821 E appears to be missing the initial shape 
![screen shot 2017-09-01 at 18 43 22](https://user-images.githubusercontent.com/4839211/29981412-7ef01478-8f45-11e7-8b78-95fa3144de1c.png)

See https://r12a.github.io/mongolian-variants/#char1821

**Comment by lianghai** [comment]
See the list in section 1.2.2, "The following graphemes are excluded from the analysis for Hudum".

**Comment by lianghai** [comment]
It's a historical form and is simply not used in modern Hudum. See the list of excluded variants in section 1.2.2 under "The following graphemes are excluded from the analysis for Hudum".

**Comment by r12a** [comment]
Ah, i missed that. Thanks.
