### ISSUE TITLE
U+1822 medi missing glyph in 1.2.2

### ISSUE THREAD

**Issue by r12a** [w3c/mlreq#14]
In addition to it's errors, the list of glyphs in TUS is missing some glyph forms that have been identified in DS01 and WG2 (and agreed with font experts over the past couple of years).  One of those glyph shapes is
![screen shot 2017-09-01 at 18 51 52](https://user-images.githubusercontent.com/4839211/29981705-aa871e00-8f46-11e7-8d42-38018f18fc87.png)
which is an alternate medial form for U+1822. See https://r12a.github.io/mongolian-variants/#char1822

Why is this omitted from the chart in 1.2.2 ?

**Comment by r12a** [comment]
Sorry @lianghai that was my mistake!  You were right, and i should have said 1.2.2.  Apologies.

**Comment by lianghai** [comment]
@r12a Oh, cool… Then I'll continue to reply… :P

**Comment by lianghai** [comment]
The double-long-tooth variant for `I.medi` is desired for a _phonetic encoding_ when `I.medi` is precede by a vowel and the preceding vowel doesn't already end with a long-tooth yet.

— But it's not relevant for a graphetic approach. No matter how hard people debate on it, be it `<I>` or `<Y>` or `<Y hookless, I>` or what, graphetically it's a sequence of graphemes: `<long tooth, long tooth>`. Therefore we don't even try to add it to the variant set of TUS 10.0.

See also section 2.3.

**Comment by r12a** [comment]
ok, thanks for the explanation. 

I guess my confusion was more with what's the table sets out to show in 1.2.2.  I saw a cell representing U+1820 A isol 3, which iiuc is composed of two graphetic characters, and so assumed that things like double long tooth above should also appear in the table. I guess it depends on what 'variant set' means - i was trying to work that out by looking at what's in the table. I suppose i'm not entirely clear about what that table represents and what belongs in and what doesn't.

**Comment by lianghai** [comment]
Ah I see. The variant set is defined in section 1.2.1 (ie, Unicode 10.0 with editorial and mismatch corrections). I'll clarify and emphasize this in the next revision. Actually, I plan to move section 1.2 to appendix because I've realized that looking at the reanalysis without seeing examples first can be confusing.
