### ISSUE TITLE
The caret movement by hitting arrow keys need to be corrected and unified on different browsers.

### ISSUE THREAD

**Issue by aronsoyol** [w3c/mlreq#16]
Please refer to the following URL that includes a contenteditable div in vertical writing mode.

[https://aronsoyol.github.io/caret_test/](https://aronsoyol.github.io/caret_test/)

The caret movement by hitting arrow keys behaves incorrectly on Chrome and Edge. It behaves correctly on the FireFox only.

**Comment by r12a** [comment]
Moved this to the above location for better visibility and tracking.
