### ISSUE TITLE
Mention right-to-left vertical text?

### ISSUE THREAD

**Issue by xfq** [w3c/mlreq#19]
In [GB/T 26233-2010 § 4.1.1](https://bug-attachments.documentfoundation.org/attachment.cgi?id=129563) (translated into English by me):

> Mongolian text general editing software should support the vertical writing mode of Mongolian text. Figure 1 shows two ways of writing from left to right and from right to left.

<img width="851" alt="fig1" src="https://user-images.githubusercontent.com/2863444/45349561-2f90f480-b5e4-11e8-9e5b-f8a5e16c689d.png">

> ↑ (Figure 1) ↑

> In the user interface, the "writing mode" option should be provided. Mongolian text's default writing mode should be: the characters are arranged from top to bottom, and the lines are arranged from left to right.

It seems that Mongolian has right-to-left vertical text too. Should we mention it in mlreq?

**Comment by badaa** [comment]
No!
It's unreadable and to cause quite a headache as Mongolian. If you have translated it correctly, then it has to be removed from this document. I tend to think authors wanted to show incorrect direction as example of right image.
There was common failed attempt to support vertical Left-to-Right direction. Someone, who cannot manage frame flow, implemented such a poor solution, which is setting text flow to Right-To-Left and rotating the frame 270°.  
The implementation of Left-to-Right direction is most complex task. Fortunately, it is supported by every browser in recent. Current real problem to Mongolian support is, there exist too many wrong directions for encoding, for font implementations, etc..
We need to redirect it to correct way.

**Comment by lianghai** [comment]
@xfq The intention of the paragraph above the figure is unclear and confusing. I’d prefer to avoid bringing this into MLReq before some clarification can be obtained from GB/T 26233’s authors.

**Comment by r12a** [comment]
@xfq do you want to seek clarification from the authors, or should i just close this issue?

**Comment by xfq** [comment]
I haven't been able to contact the authors yet, but since I failed to find a single example of right-to-left vertical Mongolian text after a lot of researching, I think we can close this issue.
